provider: signalfx
major-version: 7
makeTemplate: bridged
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: aws
    version: "4.10.0"
team: ecosystem
pulumiConvert: 1
registryDocs: true
esc:
  enabled: true
  environment: imports/github-secrets # No repo-specific secrets.

