// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DataLinkTargetSplunkArgs extends com.pulumi.resources.ResourceArgs {

    public static final DataLinkTargetSplunkArgs Empty = new DataLinkTargetSplunkArgs();

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="propertyKeyMapping")
    private @Nullable Output<Map<String,String>> propertyKeyMapping;

    public Optional<Output<Map<String,String>>> propertyKeyMapping() {
        return Optional.ofNullable(this.propertyKeyMapping);
    }

    private DataLinkTargetSplunkArgs() {}

    private DataLinkTargetSplunkArgs(DataLinkTargetSplunkArgs $) {
        this.name = $.name;
        this.propertyKeyMapping = $.propertyKeyMapping;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DataLinkTargetSplunkArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DataLinkTargetSplunkArgs $;

        public Builder() {
            $ = new DataLinkTargetSplunkArgs();
        }

        public Builder(DataLinkTargetSplunkArgs defaults) {
            $ = new DataLinkTargetSplunkArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder propertyKeyMapping(@Nullable Output<Map<String,String>> propertyKeyMapping) {
            $.propertyKeyMapping = propertyKeyMapping;
            return this;
        }

        public Builder propertyKeyMapping(Map<String,String> propertyKeyMapping) {
            return propertyKeyMapping(Output.of(propertyKeyMapping));
        }

        public DataLinkTargetSplunkArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("DataLinkTargetSplunkArgs", "name");
            }
            return $;
        }
    }

}
