// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Gcp.Inputs
{

    public sealed class IntegrationProjectWifConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        [Input("wifConfig", required: true)]
        public Input<string> WifConfig { get; set; } = null!;

        public IntegrationProjectWifConfigGetArgs()
        {
        }
        public static new IntegrationProjectWifConfigGetArgs Empty => new IntegrationProjectWifConfigGetArgs();
    }
}
