// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package signalfx

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-signalfx/sdk/v7/go/signalfx/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source is responsible for capturing all the built in content available for the user so that they can be used within their own dashboard groups.
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-signalfx/sdk/v7/go/signalfx"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			example, err := signalfx.GetBuiltinDashboards(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("all-dashboards", example)
//			// # A simple example making a reference to a specific dashboard group and dashboard.
//			_, err = signalfx.NewDashboardGroup(ctx, "my-service-dashboard-group", &signalfx.DashboardGroupArgs{
//				Name: pulumi.String("Example Dashboard Group"),
//				Dashboards: signalfx.DashboardGroupDashboardArray{
//					&signalfx.DashboardGroupDashboardArgs{
//						DashboardId:  pulumi.String(example.Results.AWS_ECS.ECSService),
//						NameOverride: pulumi.String("My Awesome Service ECS Dashboard"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// Deprecated: signalfx.index/builtindashboards.BuiltinDashboards has been deprecated in favor of signalfx.index/getbuiltindashboards.getBuiltinDashboards
func BuiltinDashboards(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*BuiltinDashboardsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv BuiltinDashboardsResult
	err := ctx.Invoke("signalfx:index/builtinDashboards:BuiltinDashboards", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by BuiltinDashboards.
type BuiltinDashboardsResult struct {
	// Map of the builtin content dashboard groups and their associated dashboards. The keys are the dashboard group names and the values are maps of dashboard names to their IDs.
	Results map[string]map[string]string `pulumi:"results"`
}

func BuiltinDashboardsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) BuiltinDashboardsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (BuiltinDashboardsResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("signalfx:index/builtinDashboards:BuiltinDashboards", nil, BuiltinDashboardsResultOutput{}, options).(BuiltinDashboardsResultOutput), nil
	}).(BuiltinDashboardsResultOutput)
}

// A collection of values returned by BuiltinDashboards.
type BuiltinDashboardsResultOutput struct{ *pulumi.OutputState }

func (BuiltinDashboardsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BuiltinDashboardsResult)(nil)).Elem()
}

func (o BuiltinDashboardsResultOutput) ToBuiltinDashboardsResultOutput() BuiltinDashboardsResultOutput {
	return o
}

func (o BuiltinDashboardsResultOutput) ToBuiltinDashboardsResultOutputWithContext(ctx context.Context) BuiltinDashboardsResultOutput {
	return o
}

// Map of the builtin content dashboard groups and their associated dashboards. The keys are the dashboard group names and the values are maps of dashboard names to their IDs.
func (o BuiltinDashboardsResultOutput) Results() pulumi.StringMapMapOutput {
	return o.ApplyT(func(v BuiltinDashboardsResult) map[string]map[string]string { return v.Results }).(pulumi.StringMapMapOutput)
}

func init() {
	pulumi.RegisterOutputType(BuiltinDashboardsResultOutput{})
}
