// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Outputs
{

    [OutputType]
    public sealed class DashboardGroupDashboard
    {
        /// <summary>
        /// The ID of the association between the dashboard group and the dashboard
        /// </summary>
        public readonly string? ConfigId;
        /// <summary>
        /// The dashboard id to mirror
        /// </summary>
        public readonly string DashboardId;
        /// <summary>
        /// The description that will override the original dashboards's description.
        /// </summary>
        public readonly string? DescriptionOverride;
        /// <summary>
        /// The description that will override the original dashboards's description.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardGroupDashboardFilterOverride> FilterOverrides;
        /// <summary>
        /// The name that will override the original dashboards's name.
        /// </summary>
        public readonly string? NameOverride;
        /// <summary>
        /// Dashboard variable to apply to each chart in the dashboard
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardGroupDashboardVariableOverride> VariableOverrides;

        [OutputConstructor]
        private DashboardGroupDashboard(
            string? configId,

            string dashboardId,

            string? descriptionOverride,

            ImmutableArray<Outputs.DashboardGroupDashboardFilterOverride> filterOverrides,

            string? nameOverride,

            ImmutableArray<Outputs.DashboardGroupDashboardVariableOverride> variableOverrides)
        {
            ConfigId = configId;
            DashboardId = dashboardId;
            DescriptionOverride = descriptionOverride;
            FilterOverrides = filterOverrides;
            NameOverride = nameOverride;
            VariableOverrides = variableOverrides;
        }
    }
}
