// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Outputs
{

    [OutputType]
    public sealed class MetricRulesetAggregationRule
    {
        /// <summary>
        /// Aggregator object
        /// </summary>
        public readonly ImmutableArray<Outputs.MetricRulesetAggregationRuleAggregator> Aggregators;
        /// <summary>
        /// Information about an aggregation rule
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// When false, this rule will not generate aggregated MTSs
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Matcher object
        /// </summary>
        public readonly ImmutableArray<Outputs.MetricRulesetAggregationRuleMatcher> Matchers;
        /// <summary>
        /// name of the aggregation rule
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private MetricRulesetAggregationRule(
            ImmutableArray<Outputs.MetricRulesetAggregationRuleAggregator> aggregators,

            string? description,

            bool enabled,

            ImmutableArray<Outputs.MetricRulesetAggregationRuleMatcher> matchers,

            string? name)
        {
            Aggregators = aggregators;
            Description = description;
            Enabled = enabled;
            Matchers = matchers;
            Name = name;
        }
    }
}
