// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Outputs
{

    [OutputType]
    public sealed class MetricRulesetAggregationRuleMatcherFilter
    {
        /// <summary>
        /// Flag specifying equals or not equals
        /// </summary>
        public readonly bool Not;
        /// <summary>
        /// Name of dimension to match
        /// </summary>
        public readonly string Property;
        /// <summary>
        /// List of property values to match
        /// </summary>
        public readonly ImmutableArray<string> PropertyValues;

        [OutputConstructor]
        private MetricRulesetAggregationRuleMatcherFilter(
            bool not,

            string property,

            ImmutableArray<string> propertyValues)
        {
            Not = not;
            Property = property;
            PropertyValues = propertyValues;
        }
    }
}
