// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class DashboardGroupDashboardVariableOverride {
    /**
     * @return The name of a dimension to filter against.
     * 
     */
    private String property;
    /**
     * @return A list of values to be used with the `property`, they will be combined via `OR`.
     * 
     */
    private @Nullable List<String> values;
    /**
     * @return A list of strings of suggested values for this variable; these suggestions will receive priority when values are autosuggested for this variable.
     * 
     */
    private @Nullable List<String> valuesSuggesteds;

    private DashboardGroupDashboardVariableOverride() {}
    /**
     * @return The name of a dimension to filter against.
     * 
     */
    public String property() {
        return this.property;
    }
    /**
     * @return A list of values to be used with the `property`, they will be combined via `OR`.
     * 
     */
    public List<String> values() {
        return this.values == null ? List.of() : this.values;
    }
    /**
     * @return A list of strings of suggested values for this variable; these suggestions will receive priority when values are autosuggested for this variable.
     * 
     */
    public List<String> valuesSuggesteds() {
        return this.valuesSuggesteds == null ? List.of() : this.valuesSuggesteds;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardGroupDashboardVariableOverride defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String property;
        private @Nullable List<String> values;
        private @Nullable List<String> valuesSuggesteds;
        public Builder() {}
        public Builder(DashboardGroupDashboardVariableOverride defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.property = defaults.property;
    	      this.values = defaults.values;
    	      this.valuesSuggesteds = defaults.valuesSuggesteds;
        }

        @CustomType.Setter
        public Builder property(String property) {
            this.property = Objects.requireNonNull(property);
            return this;
        }
        @CustomType.Setter
        public Builder values(@Nullable List<String> values) {
            this.values = values;
            return this;
        }
        public Builder values(String... values) {
            return values(List.of(values));
        }
        @CustomType.Setter
        public Builder valuesSuggesteds(@Nullable List<String> valuesSuggesteds) {
            this.valuesSuggesteds = valuesSuggesteds;
            return this;
        }
        public Builder valuesSuggesteds(String... valuesSuggesteds) {
            return valuesSuggesteds(List.of(valuesSuggesteds));
        }
        public DashboardGroupDashboardVariableOverride build() {
            final var o = new DashboardGroupDashboardVariableOverride();
            o.property = property;
            o.values = values;
            o.valuesSuggesteds = valuesSuggesteds;
            return o;
        }
    }
}
