// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DashboardGrid {
    /**
     * @return List of IDs of the charts to display.
     * 
     */
    private List<String> chartIds;
    /**
     * @return How many rows every chart should take up (greater than or equal to `1`). `1` by default.
     * 
     */
    private @Nullable Integer height;
    /**
     * @return How many columns (out of a total of 12) every chart should take up (between `1` and `12`). `12` by default.
     * 
     */
    private @Nullable Integer width;

    private DashboardGrid() {}
    /**
     * @return List of IDs of the charts to display.
     * 
     */
    public List<String> chartIds() {
        return this.chartIds;
    }
    /**
     * @return How many rows every chart should take up (greater than or equal to `1`). `1` by default.
     * 
     */
    public Optional<Integer> height() {
        return Optional.ofNullable(this.height);
    }
    /**
     * @return How many columns (out of a total of 12) every chart should take up (between `1` and `12`). `12` by default.
     * 
     */
    public Optional<Integer> width() {
        return Optional.ofNullable(this.width);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardGrid defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> chartIds;
        private @Nullable Integer height;
        private @Nullable Integer width;
        public Builder() {}
        public Builder(DashboardGrid defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.chartIds = defaults.chartIds;
    	      this.height = defaults.height;
    	      this.width = defaults.width;
        }

        @CustomType.Setter
        public Builder chartIds(List<String> chartIds) {
            if (chartIds == null) {
              throw new MissingRequiredPropertyException("DashboardGrid", "chartIds");
            }
            this.chartIds = chartIds;
            return this;
        }
        public Builder chartIds(String... chartIds) {
            return chartIds(List.of(chartIds));
        }
        @CustomType.Setter
        public Builder height(@Nullable Integer height) {

            this.height = height;
            return this;
        }
        @CustomType.Setter
        public Builder width(@Nullable Integer width) {

            this.width = width;
            return this;
        }
        public DashboardGrid build() {
            final var _resultValue = new DashboardGrid();
            _resultValue.chartIds = chartIds;
            _resultValue.height = height;
            _resultValue.width = width;
            return _resultValue;
        }
    }
}
