// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class DataLinkTargetSplunk {
    /**
     * @return User-assigned target name. Use this value to differentiate between the link targets for a data link object.
     * 
     */
    private String name;
    /**
     * @return Describes the relationship between Splunk Observability Cloud metadata keys and external system properties when the key names are different.
     * 
     */
    private @Nullable Map<String,String> propertyKeyMapping;

    private DataLinkTargetSplunk() {}
    /**
     * @return User-assigned target name. Use this value to differentiate between the link targets for a data link object.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Describes the relationship between Splunk Observability Cloud metadata keys and external system properties when the key names are different.
     * 
     */
    public Map<String,String> propertyKeyMapping() {
        return this.propertyKeyMapping == null ? Map.of() : this.propertyKeyMapping;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DataLinkTargetSplunk defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private @Nullable Map<String,String> propertyKeyMapping;
        public Builder() {}
        public Builder(DataLinkTargetSplunk defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.propertyKeyMapping = defaults.propertyKeyMapping;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("DataLinkTargetSplunk", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder propertyKeyMapping(@Nullable Map<String,String> propertyKeyMapping) {

            this.propertyKeyMapping = propertyKeyMapping;
            return this;
        }
        public DataLinkTargetSplunk build() {
            final var _resultValue = new DataLinkTargetSplunk();
            _resultValue.name = name;
            _resultValue.propertyKeyMapping = propertyKeyMapping;
            return _resultValue;
        }
    }
}
