// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DataLinkTargetSignalfxDashboard {
    /**
     * @return SignalFx-assigned ID of the dashboard link target&#39;s dashboard group
     * 
     */
    private String dashboardGroupId;
    /**
     * @return SignalFx-assigned ID of the dashboard link target
     * 
     */
    private String dashboardId;
    /**
     * @return Flag that designates a target as the default for a data link object. `true` by default
     * 
     */
    private @Nullable Boolean isDefault;
    /**
     * @return User-assigned target name. Use this value to differentiate between the link targets for a data link object.
     * 
     */
    private String name;

    private DataLinkTargetSignalfxDashboard() {}
    /**
     * @return SignalFx-assigned ID of the dashboard link target&#39;s dashboard group
     * 
     */
    public String dashboardGroupId() {
        return this.dashboardGroupId;
    }
    /**
     * @return SignalFx-assigned ID of the dashboard link target
     * 
     */
    public String dashboardId() {
        return this.dashboardId;
    }
    /**
     * @return Flag that designates a target as the default for a data link object. `true` by default
     * 
     */
    public Optional<Boolean> isDefault() {
        return Optional.ofNullable(this.isDefault);
    }
    /**
     * @return User-assigned target name. Use this value to differentiate between the link targets for a data link object.
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DataLinkTargetSignalfxDashboard defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String dashboardGroupId;
        private String dashboardId;
        private @Nullable Boolean isDefault;
        private String name;
        public Builder() {}
        public Builder(DataLinkTargetSignalfxDashboard defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dashboardGroupId = defaults.dashboardGroupId;
    	      this.dashboardId = defaults.dashboardId;
    	      this.isDefault = defaults.isDefault;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder dashboardGroupId(String dashboardGroupId) {
            if (dashboardGroupId == null) {
              throw new MissingRequiredPropertyException("DataLinkTargetSignalfxDashboard", "dashboardGroupId");
            }
            this.dashboardGroupId = dashboardGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder dashboardId(String dashboardId) {
            if (dashboardId == null) {
              throw new MissingRequiredPropertyException("DataLinkTargetSignalfxDashboard", "dashboardId");
            }
            this.dashboardId = dashboardId;
            return this;
        }
        @CustomType.Setter
        public Builder isDefault(@Nullable Boolean isDefault) {

            this.isDefault = isDefault;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("DataLinkTargetSignalfxDashboard", "name");
            }
            this.name = name;
            return this;
        }
        public DataLinkTargetSignalfxDashboard build() {
            final var _resultValue = new DataLinkTargetSignalfxDashboard();
            _resultValue.dashboardGroupId = dashboardGroupId;
            _resultValue.dashboardId = dashboardId;
            _resultValue.isDefault = isDefault;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
