// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Inputs
{

    public sealed class DashboardEventOverlayArgs : global::Pulumi.ResourceArgs
    {
        [Input("color")]
        public Input<string>? Color { get; set; }

        [Input("label")]
        public Input<string>? Label { get; set; }

        [Input("line")]
        public Input<bool>? Line { get; set; }

        [Input("signal", required: true)]
        public Input<string> Signal { get; set; } = null!;

        [Input("sources")]
        private InputList<Inputs.DashboardEventOverlaySourceArgs>? _sources;
        public InputList<Inputs.DashboardEventOverlaySourceArgs> Sources
        {
            get => _sources ?? (_sources = new InputList<Inputs.DashboardEventOverlaySourceArgs>());
            set => _sources = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public DashboardEventOverlayArgs()
        {
        }
        public static new DashboardEventOverlayArgs Empty => new DashboardEventOverlayArgs();
    }
}
