// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Inputs
{

    public sealed class DashboardPermissionsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("acls")]
        private InputList<Inputs.DashboardPermissionsAclGetArgs>? _acls;

        /// <summary>
        /// The custom access control list for this dashboard
        /// </summary>
        public InputList<Inputs.DashboardPermissionsAclGetArgs> Acls
        {
            get => _acls ?? (_acls = new InputList<Inputs.DashboardPermissionsAclGetArgs>());
            set => _acls = value;
        }

        /// <summary>
        /// The ID of the dashboard group that this dashboard inherits permissions from
        /// </summary>
        [Input("parent")]
        public Input<string>? Parent { get; set; }

        public DashboardPermissionsGetArgs()
        {
        }
        public static new DashboardPermissionsGetArgs Empty => new DashboardPermissionsGetArgs();
    }
}
