// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SignalFx.Inputs
{

    public sealed class TimeChartAxisLeftGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("highWatermark")]
        public Input<double>? HighWatermark { get; set; }

        [Input("highWatermarkLabel")]
        public Input<string>? HighWatermarkLabel { get; set; }

        [Input("label")]
        public Input<string>? Label { get; set; }

        [Input("lowWatermark")]
        public Input<double>? LowWatermark { get; set; }

        [Input("lowWatermarkLabel")]
        public Input<string>? LowWatermarkLabel { get; set; }

        [Input("maxValue")]
        public Input<double>? MaxValue { get; set; }

        [Input("minValue")]
        public Input<double>? MinValue { get; set; }

        [Input("watermarks")]
        private InputList<Inputs.TimeChartAxisLeftWatermarkGetArgs>? _watermarks;
        public InputList<Inputs.TimeChartAxisLeftWatermarkGetArgs> Watermarks
        {
            get => _watermarks ?? (_watermarks = new InputList<Inputs.TimeChartAxisLeftWatermarkGetArgs>());
            set => _watermarks = value;
        }

        public TimeChartAxisLeftGetArgs()
        {
        }
        public static new TimeChartAxisLeftGetArgs Empty => new TimeChartAxisLeftGetArgs();
    }
}
