// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.pagerduty;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.signalfx.Utilities;
import com.pulumi.signalfx.pagerduty.inputs.GetIntegrationArgs;
import com.pulumi.signalfx.pagerduty.inputs.GetIntegrationPlainArgs;
import com.pulumi.signalfx.pagerduty.outputs.GetIntegrationResult;
import java.util.concurrent.CompletableFuture;

public final class PagerdutyFunctions {
    /**
     * Use this data source to get information on an existing PagerDuty integration.
     * 
     * ## Example
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.signalfx.pagerduty.PagerdutyFunctions;
     * import com.pulumi.signalfx.pagerduty.inputs.GetIntegrationArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var pdIntegration = PagerdutyFunctions.getIntegration(GetIntegrationArgs.builder()
     *             .name(&#34;PD-Integration&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     * ## Arguments
     * 
     * * `name` - Specify the exact name of the desired PagerDuty integration
     * 
     * ## Attributes
     * 
     * * `id` - The ID of the integration.
     * * `name` - The name of the integration.
     * * `enabled` - Whether the integration is enabled.
     * 
     */
    public static Output<GetIntegrationResult> getIntegration(GetIntegrationArgs args) {
        return getIntegration(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to get information on an existing PagerDuty integration.
     * 
     * ## Example
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.signalfx.pagerduty.PagerdutyFunctions;
     * import com.pulumi.signalfx.pagerduty.inputs.GetIntegrationArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var pdIntegration = PagerdutyFunctions.getIntegration(GetIntegrationArgs.builder()
     *             .name(&#34;PD-Integration&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     * ## Arguments
     * 
     * * `name` - Specify the exact name of the desired PagerDuty integration
     * 
     * ## Attributes
     * 
     * * `id` - The ID of the integration.
     * * `name` - The name of the integration.
     * * `enabled` - Whether the integration is enabled.
     * 
     */
    public static CompletableFuture<GetIntegrationResult> getIntegrationPlain(GetIntegrationPlainArgs args) {
        return getIntegrationPlain(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to get information on an existing PagerDuty integration.
     * 
     * ## Example
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.signalfx.pagerduty.PagerdutyFunctions;
     * import com.pulumi.signalfx.pagerduty.inputs.GetIntegrationArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var pdIntegration = PagerdutyFunctions.getIntegration(GetIntegrationArgs.builder()
     *             .name(&#34;PD-Integration&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     * ## Arguments
     * 
     * * `name` - Specify the exact name of the desired PagerDuty integration
     * 
     * ## Attributes
     * 
     * * `id` - The ID of the integration.
     * * `name` - The name of the integration.
     * * `enabled` - Whether the integration is enabled.
     * 
     */
    public static Output<GetIntegrationResult> getIntegration(GetIntegrationArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("signalfx:pagerduty/getIntegration:getIntegration", TypeShape.of(GetIntegrationResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to get information on an existing PagerDuty integration.
     * 
     * ## Example
     * 
     * &lt;!--Start PulumiCodeChooser --&gt;
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.signalfx.pagerduty.PagerdutyFunctions;
     * import com.pulumi.signalfx.pagerduty.inputs.GetIntegrationArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         final var pdIntegration = PagerdutyFunctions.getIntegration(GetIntegrationArgs.builder()
     *             .name(&#34;PD-Integration&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * &lt;!--End PulumiCodeChooser --&gt;
     * 
     * ## Arguments
     * 
     * * `name` - Specify the exact name of the desired PagerDuty integration
     * 
     * ## Attributes
     * 
     * * `id` - The ID of the integration.
     * * `name` - The name of the integration.
     * * `enabled` - Whether the integration is enabled.
     * 
     */
    public static CompletableFuture<GetIntegrationResult> getIntegrationPlain(GetIntegrationPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("signalfx:pagerduty/getIntegration:getIntegration", TypeShape.of(GetIntegrationResult.class), args, Utilities.withVersion(options));
    }
}
