// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.gcp.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.signalfx.gcp.outputs.GetServicesService;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetServicesResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private final String id;
    private final @Nullable List<GetServicesService> services;

    @CustomType.Constructor
    private GetServicesResult(
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("services") @Nullable List<GetServicesService> services) {
        this.id = id;
        this.services = services;
    }

    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetServicesService> services() {
        return this.services == null ? List.of() : this.services;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServicesResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String id;
        private @Nullable List<GetServicesService> services;

        public Builder() {
    	      // Empty
        }

        public Builder(GetServicesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.services = defaults.services;
        }

        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder services(@Nullable List<GetServicesService> services) {
            this.services = services;
            return this;
        }
        public Builder services(GetServicesService... services) {
            return services(List.of(services));
        }        public GetServicesResult build() {
            return new GetServicesResult(id, services);
        }
    }
}
