// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.signalfx.gcp.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class IntegrationProjectWifConfig {
    private String projectId;
    private String wifConfig;

    private IntegrationProjectWifConfig() {}
    public String projectId() {
        return this.projectId;
    }
    public String wifConfig() {
        return this.wifConfig;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IntegrationProjectWifConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String projectId;
        private String wifConfig;
        public Builder() {}
        public Builder(IntegrationProjectWifConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.projectId = defaults.projectId;
    	      this.wifConfig = defaults.wifConfig;
        }

        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("IntegrationProjectWifConfig", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder wifConfig(String wifConfig) {
            if (wifConfig == null) {
              throw new MissingRequiredPropertyException("IntegrationProjectWifConfig", "wifConfig");
            }
            this.wifConfig = wifConfig;
            return this;
        }
        public IntegrationProjectWifConfig build() {
            final var _resultValue = new IntegrationProjectWifConfig();
            _resultValue.projectId = projectId;
            _resultValue.wifConfig = wifConfig;
            return _resultValue;
        }
    }
}
